#! /usr/bin/env python

import sys
import yaml
from bolero.controller import Controller


if __name__ == "__main__":
    config_file = "learning_config.yml"
    if len(sys.argv) > 1:
        config_file = sys.argv[-1]

    config = yaml.load(open(config_file, "r"))
    controller = Controller(config)
    controller.learn()
